Movies/Models/Session.cs
using Movies.ViewModels;

namespace Movies.Models
{
    public class Session
    {
        public Session() { }
        public int Id { get; set; }
        public int HallId { get; set; }
        public int MovieId { get; set; }
        public DateTime TimeDate { get; set; }
        public int Price { get; set; }

        public Hall Hall { get; set; }
        public Movie Movie { get; set; }
        public IEnumerable<Ticket> Tickets { get; set; }

        public Session(SessionViewModel model)
        {
            Id = model.Id;
            HallId = model.HallId;
            MovieId = model.MovieId;
            TimeDate = model.TimeDate;
            Price = model.Price;
        }
    }
}

Movies/ViewModels/SessionViewModel.cs
using Movies.Models;
using System.ComponentModel.DataAnnotations;

namespace Movies.ViewModels
{
    public class SessionViewModel
    {
        public SessionViewModel() { }

        public int Id { get; set; }
        public int HallId { get; set; }
        public string? Hall { get; set; }

        public string? Movie { get; set; }
        public int MovieId { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [Display(Prompt = "Select session time")]
        public DateTime TimeDate { get; set; }
        [Display(Prompt = "Enter price in UAH")]
        [Required(ErrorMessage = "This field is required")]
        [Range(40, 500, ErrorMessage = "Price has to be between 40 and 500")]
        public int Price { get; set; }

        public List<string>? HallTechStrList { get; set; }
        public string? HallTechString { get; set; }

        public List<Ticket>? Tickets { get; set; }

        public SessionViewModel(Session session)
        {
            Id = session.Id;
            HallId = session.HallId;
            MovieId = session.MovieId;
            TimeDate = session.TimeDate;
            Price = session.Price;

            if (session.Tickets != null) 
            {
                Tickets = session.Tickets.ToList();
            }
            if (session.Hall != null)
            {
                Hall = session.Hall.Name;
                var Hmodel = new HallViewModel(session.Hall);
                HallTechStrList = Hmodel.TechnologiesStrList;
                HallTechString = Hmodel.TechnologiesString;
            }
            if (session.Movie != null)
            {
                Movie = session.Movie.Title;
            }
        }
    }
}

Movies/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Movies.Data;
using Movies.Models;
using Movies.ViewModels;
namespace Movies.Controllers
{
    public class GenresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GenresController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Genres.Select(x => new GenreViewModel(x)).ToListAsync());
        }
        [Authorize(Roles = "Admins")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admins")]
        public async Task<IActionResult> Create(GenreViewModel genreView)
        {
            bool remote = new DataController(_context).GenresValidation(genreView.Name);
            if (ModelState.IsValid && remote)
            {
                _context.Add(new Genre(genreView));
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            if(!remote)
            {
                ModelState.AddModelError("Name", "Current genre name already exists");
            }
            return View(genreView);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                var genre = await _context.Genres.Include(g => g.Movies)
                .FirstOrDefaultAsync(m => m.Id == id);
                if (genre != null)
                {
                    return View(new GenreViewModel(genre));
                }
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles ="Admins")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                var genre = await _context.Genres
                .FindAsync(id);
                if(genre != null)
                return View(new GenreViewModel(genre));
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admins")]
        public async Task<IActionResult> Edit(GenreViewModel genreView)
        {
            bool remote = new DataController(_context).GenresValidation(genreView.Name);
            if (ModelState.IsValid && remote)
            {
                 _context.Update(new Genre(genreView));
                 await _context.SaveChangesAsync();
                 return RedirectToAction(nameof(Index));
            }
            if (!remote)
            {
                ModelState.AddModelError("Name", "Current genre name already exists");
            }
            return View(genreView);
        }
        [Authorize(Roles = "Admins")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                var genre = await _context.Genres
                .FindAsync(id);
                if(genre != null)
                return View(new GenreViewModel(genre));
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admins")]
        public async Task<IActionResult> Delete(int id)
        {
            var genre = await _context.Genres.FindAsync(id);
            if (genre != null)
            {
                _context.Remove(genre);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Movies/Controllers/HallsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Movies.Data;
using Movies.Models;
using Movies.ViewModels;

namespace Movies.Controllers
{
    public class HallsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HallsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Halls.Include(h => h.Technologies)
                    .Select(h => new HallViewModel(h))
                    .ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                var hall = await _context.Halls
                .Include(h => h.Technologies)
                .FirstOrDefaultAsync(m => m.Id == id);
                if (hall != null)
                {
                    return View(new HallViewModel(hall));
                }
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admins")]
        public IActionResult Create()
        {
            ViewBag.Technologies = _context.Technologies.ToList();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admins")]
        public async Task<IActionResult> Create(HallViewModel model, int[] TechId)
        {
            var hall = new Hall(model);
            hall.Technologies = TechId.Select(t => _context.Technologies.Find(t)).ToList()!;
            bool remote = new DataController(_context).HallsValidation(hall.Name);
            if (ModelState.IsValid && remote)
            {
                _context.Add(hall);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            if (!remote)
            {
                ModelState.AddModelError("Name", "Hall already exists");
            }
            ViewBag.Technologies = await _context.Technologies.ToListAsync();
            return View(model);
        }

        [Authorize(Roles = "Admins")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                var hall = await _context.Halls.FindAsync(id);
                if (hall != null)
                {
                    ViewBag.Technologies = _context.Technologies.ToList();
                    var selectedTech = _context.Halls.Include(h => h.Technologies)
                        .FirstOrDefault(h => h.Id == id);
                    if (selectedTech != null)
                    {
                        ViewBag.SelectedTech = selectedTech.Technologies?.Select(t => t.Id).ToList();
                    }
                    return View(new HallViewModel(hall));
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admins")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, HallViewModel model, int[] TechId)
        {
            var hall = new Hall(model);
            bool remote = new DataController(_context).HallsValidation(hall.Name, hall.Id);
            if (ModelState.IsValid && remote)
            {
                if (id != hall.Id)
                {
                    return NotFound();
                }
                ICollection<Technology> technologies = new HashSet<Technology>();
                foreach (int i in TechId)
                {
                    var technology = _context.Technologies.Find(i);
                    if (technology != null)
                    {
                        technologies.Add(technology);
                    }
                }
                var HallToUpd = _context.Halls.Include(h => h.Technologies)
                    .FirstOrDefault(h => h.Id == id);
                if (HallToUpd != null)
                {
                    HallToUpd.Name = hall.Name;
                    HallToUpd.Rows = hall.Rows;
                    HallToUpd.SeatsPerRow = hall.SeatsPerRow;
                    HallToUpd.Technologies = technologies;
                    _context.Update(HallToUpd);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            if (!remote)
            {
                ModelState.AddModelError("Name", "Hall already exists");
            }
            ViewBag.Technologies = _context.Technologies.ToList();
            return View(model) ;
        }

        [Authorize(Roles = "Admins")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                var hall = await _context.Halls
                    .Include(h => h.Technologies)
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (hall != null)
                {
                    return View(new HallViewModel(hall));
                }
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admins")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hall = await _context.Halls.FindAsync(id);
            if (hall != null)
            {
                _context.Halls.Remove(hall);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Movies/Controllers/SessionController.cs
using Microsoft.AspNetCore.Mvc;
using Movies.Models;
using Movies.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Movies.ViewModels;
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace Movies.Controllers
{
    public class SessionController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SessionController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var movies = _db.Movies
                .Include
                (m => m.Sessions!
                .OrderBy(s => s.TimeDate))
                .ThenInclude(s => s.Hall)
                .Select(m => new MovieViewModel(m))
                .ToListAsync();
            return View(await movies);
        }
        [Authorize(Roles = "Admins")]
        public IActionResult Create()
        {
            ViewBag.Movies = _db.Movies.ToList();
            ViewBag.Halls = _db.Halls.ToList();
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admins")]
        public IActionResult Create(SessionViewModel sessionViewModel)
        {
            if (ModelState.IsValid)
            {
                _db.Sessions.Add(new Session(sessionViewModel));
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Movies = _db.Movies.ToList();
            ViewBag.Halls = _db.Halls.ToList();
            return View(sessionViewModel);
        }
        [Authorize(Roles = "Admins")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                var Session = await _db.Sessions.Include(s => s.Hall).Include(s => s.Movie)
                .FirstOrDefaultAsync(s => s.Id == id);
                ViewBag.Movies = _db.Movies.ToList();
                ViewBag.Halls = _db.Halls.ToList();
                return View(new SessionViewModel(Session!));
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admins")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SessionViewModel vmodel)
        {
            var session = new Session(vmodel);
            if (ModelState.IsValid)
            {
                if (id == session.Id)
                {
                    _db.Update(session);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return NotFound();
            }
            ViewBag.Movies = _db.Movies.ToList();
            ViewBag.Halls = _db.Halls.ToList();
            return View(new SessionViewModel(session));
        }

        [Authorize(Roles = "Admins")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                var Session = await _db.Sessions.Include(s => s.Hall).Include(s => s.Movie)
                .FirstOrDefaultAsync(s => s.Id == id);
                return View(new SessionViewModel(Session!));
            }
            return RedirectToAction("Index");
        }

        // POST: Sessions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admins")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var session = await _db.Sessions.FindAsync(id);
            if (session != null)
            {
                _db.Sessions.Remove(session);
                var ticketsToRemove = _db.Tickets.Where(t => t.SessionId == session.Id);
                _db.Tickets.RemoveRange(ticketsToRemove);
                await _db.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                var Session = await _db.Sessions.Include(s => s.Hall).Include(s => s.Movie)
                .FirstOrDefaultAsync(s => s.Id == id);
                return View(new SessionViewModel(Session!));
            }
            return RedirectToAction("Index");
        }
    }
}

Movies/Views/Shared/SessionsTable.cshtml
@model List<Movies.ViewModels.SessionViewModel>

@{
	bool Admin = User.IsInRole("Admins");
}

<table class="table">
	<thead>
		<tr>
			<th>
				Time and Date
			</th>
			<th>
				Hall
			</th>
			<th>
				Price 
			</th>
			@if (Admin)
			{
				<th>
				</th>
			}
			<th>
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr class="@(item.TimeDate < DateTime.Now? "unav_session" : "" )">
				<td>
					@Html.DisplayFor(modelItem => item.TimeDate)
				</td>
				<td>
					@item.Hall
				</td>
				<td>
					@item.Price UAH
				</td>
				@if (Admin)
				{
					<td>
						<a asp-action="Edit" asp-route-id="@item.Id">Edit</a><span> | </span>
						<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
					</td>
				}
				<td>
					<a href="@(item.TimeDate < DateTime.Now ? "" : $"/Tickets/Create/{item.Id}")">
						<button @(item.TimeDate < DateTime.Now ? "disabled" : "")>Book a seat</button>
					</a>
				</td>
			</tr>
		}
	</tbody>
</table>

Movies/Views/Shared/TicketList.cshtml
@model List<Movies.ViewModels.TicketViewModel>
@{
    bool Admin = User.IsInRole("Admins");
}
<table class="table">
    <thead>
        <tr>
            <th>
                Movie
            </th>
            <th>
                Date and time
            </th>
            <th>
                Row
            </th>
            <th>
                Seat
            </th>
            <th>
                Hall
            </th>
            <th>
                Price
            </th>
            @if (Admin)
            {
                <th></th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var t in Model)
        {
            <tr>
                <td>
                    <a href="/Movies/Details/@t.MovieId">@t.Movie</a>
                </td>
                <td>
                    @t.SessionTime
                </td>
                <td>
                    @t.SeatRow
                </td>
                <td>
                    @t.SeatNum
                </td>
                <td>
                    @t.Hall
                </td>
                <td>
                    @t.Price UAH
                </td>
                @if (Admin)
                {
                <td>
                        <a asp-action="Delete" asp-route-id="@t.Id">Delete</a>
                </td>
                }
            </tr>
        }
    </tbody>
</table>

Movies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Movies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Movies.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-xl navbar-toggleable-xl navbar-light bg-transparent border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Movies</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon navbar-light"></span>
                </button>
                <div class="navbar-collapse collapse d-xl-inline-flex justify-content-between">
                    <partial name="_LayoutPartial"/>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Movies - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
  
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Movies/Views/Shared/_LayoutPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager
@{
    if (SignInManager.IsSignedIn(User) && User.IsInRole("Admins"))
    {
        <ul class="main-list">
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Session" asp-action="Index">Sessions</a>
                <ul class="sub-list">
                    <li>
                        <a asp-area="" asp-controller="Session" asp-action="Create">Create</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a>
                <ul class="sub-list">
                    <li>
                        <a asp-area="" asp-controller="Tickets" asp-action="Create">Create</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
                <ul class="sub-list">
                    <li>
                        <a asp-area="" asp-controller="Genres" asp-action="Create">Create</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Halls" asp-action="Index">Halls</a>
                <ul class="sub-list">
                    <li>
                        <a asp-area="" asp-controller="Halls" asp-action="Create">Create</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                <ul class="sub-list">
                    <li>
                        <a asp-area="" asp-controller="Movies" asp-action="Create">Create</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Purchases" asp-action="Index">Purchases</a>
                <ul class="sub-list">
                    <li>
                        <a asp-area="" asp-controller="Purchases" asp-action="Create">Create</a>
                    </li>
                </ul>
            </li>
        </ul>
    }
    else
    {
        <ul class="main-list">
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Session" asp-action="Index">Sessions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Halls" asp-action="Index">Halls</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
            </li>
        </ul>
    }
}
<hr />